### ISSUE TITLE
IntoParams doesn't work if not in the same file as handler

### ISSUE THREAD

**Issue by RemiKalbe** [juhaku/utoipa#157]
I have the following handler:
```rust
#[utoipa::path(
    context_path = "/api/v1/private/workers/{worker_id}/pipe_transports",
    responses(
        (status = 200, description = "Pipe Transport created"),
    ),
    tag = "pipe_transports"
  )]
#[post("")]
#[tracing::instrument(skip(state))]
pub async fn create(
    req_path: Path<request::CreatePipeTransportRequestPath>,
    state: Data<crate::state::AppStateHandle>,
) -> Result<Json<response::CreatePipeTransportResponse>, AppError> {
    .......
}
```
with the following struct for the Path **in a different file** (`request::CreatePipeTransportRequestPath`)
```rust
#[derive(Debug, Deserialize, Serialize, IntoParams)]
pub struct CreatePipeTransportRequestPath {
    pub worker_id: WorkerId,
}
```
this result in the following error:

> the trait bound `handlers::workers::pipe_transports::request::CreatePipeTransportRequestPath: utoipa::ParameterIn` is not satisfied
the trait `utoipa::ParameterIn` is not implemented for `handlers::workers::pipe_transports::request::CreatePipeTransportRequestPath`

but, if I put `CreatePipeTransportRequestPath` in the same file as my `create` handler, I don't have any error.

**Comment by juhaku** [comment]
Hi, good finding. This should be fixed with next release and actually with this PR: https://github.com/juhaku/utoipa/pull/156. The `ParameterIn` trait will  be removed completely so it wont cause any unnecessary issues.

**Comment by RemiKalbe** [comment]
Indeed it works now! Thank you very much 😁

**Comment by RemiKalbe** [comment]
It actually still doesn't work. I do not get the error yes, but nothing is generated
<img width="321" alt="CleanShot 2022-06-11 at 13 50 07@2x" src="https://user-images.githubusercontent.com/8604600/173186632-ca3d63c8-fa1d-4c71-ac29-c93f2bca14db.png">
if i put the struct in the same file then it is generated as expected
<img width="601" alt="CleanShot 2022-06-11 at 13 50 30@2x" src="https://user-images.githubusercontent.com/8604600/173186646-cb95b19a-5c48-42d0-b297-66a1134d4f2b.png">
(I'm using another struct in this screenshot)

**Comment by juhaku** [comment]
Right, now there is a another issue hindering this from functioning. Originally it was not not desingned to support such case where the type would be in another module. I will address this in next PR, but current workaround is to declare the type in same module as the handler is defined.
